-- CHARGE_REQUEST 테이블 생성 SQL
CREATE TABLE CHARGE_REQUEST (
    REQ_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'W' CHECK (STATUS IN ('W', 'A', 'R')), -- W:대기, A:승인, R:거부
    REQUEST_DATE DATE DEFAULT SYSDATE,
    APPROVE_DATE DATE,
    CONSTRAINT FK_CHARGE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES USERS(MEMBER_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_CHARGE_REQUEST_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 테스트 데이터 삽입
INSERT INTO CHARGE_REQUEST (REQ_ID, MEMBER_ID, AMOUNT, STATUS, REQUEST_DATE) 
VALUES (SEQ_CHARGE_REQUEST_ID.NEXTVAL, 'user001', 500000, 'W', SYSDATE);

INSERT INTO CHARGE_REQUEST (REQ_ID, MEMBER_ID, AMOUNT, STATUS, REQUEST_DATE) 
VALUES (SEQ_CHARGE_REQUEST_ID.NEXTVAL, 'user002', 1000000, 'W', SYSDATE-1);

INSERT INTO CHARGE_REQUEST (REQ_ID, MEMBER_ID, AMOUNT, STATUS, REQUEST_DATE, APPROVE_DATE) 
VALUES (SEQ_CHARGE_REQUEST_ID.NEXTVAL, 'user003', 300000, 'A', SYSDATE-2, SYSDATE-1);

INSERT INTO CHARGE_REQUEST (REQ_ID, MEMBER_ID, AMOUNT, STATUS, REQUEST_DATE, APPROVE_DATE) 
VALUES (SEQ_CHARGE_REQUEST_ID.NEXTVAL, 'user004', 200000, 'R', SYSDATE-3, SYSDATE-2);

COMMIT;