-- WISHLIST 테이블 생성 SQL
-- Oracle Database용

-- 기존 테이블이 있다면 삭제 (선택사항)
-- DROP TABLE WISHLIST;

-- WISHLIST 테이블 생성
CREATE TABLE WISHLIST (
    WISHLIST_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_WISHLIST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISHLIST_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UK_WISHLIST_MEMBER_PRODUCT UNIQUE (MEMBER_ID, PRODUCT_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_WISHLIST_ID
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

-- 인덱스 생성 (성능 향상을 위해)
CREATE INDEX IDX_WISHLIST_MEMBER_ID ON WISHLIST(MEMBER_ID);
CREATE INDEX IDX_WISHLIST_PRODUCT_ID ON WISHLIST(PRODUCT_ID);
CREATE INDEX IDX_WISHLIST_CREATED_AT ON WISHLIST(CREATED_AT);

-- 샘플 데이터 (선택사항)
-- INSERT INTO WISHLIST (WISHLIST_ID, MEMBER_ID, PRODUCT_ID) VALUES (SEQ_WISHLIST_ID.NEXTVAL, 'user01', 1);
-- INSERT INTO WISHLIST (WISHLIST_ID, MEMBER_ID, PRODUCT_ID) VALUES (SEQ_WISHLIST_ID.NEXTVAL, 'user01', 2);

-- 확인
SELECT * FROM WISHLIST;

COMMIT;