-- 마일리지 거래 내역 테이블 생성 SQL

-- 1. TRANSACTION_LOG 테이블 생성
CREATE TABLE TRANSACTION_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(10) NOT NULL CHECK (TRANSACTION_TYPE IN ('B', 'R', 'S', 'C', 'W')),
    -- B: 입찰(Bid), R: 환불(Refund), S: 판매(Sale), C: 충전(Charge), W: 낙찰(Win)
    AMOUNT NUMBER NOT NULL,
    TRANSACTION_TIME DATE DEFAULT SYSDATE,
    RELATED_ITEM_ID NUMBER,
    DESCRIPTION VARCHAR2(200),
    CONSTRAINT FK_TRANSACTION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES USERS(MEMBER_ID)
);

-- 2. TRANSACTION_LOG 시퀀스 생성
CREATE SEQUENCE TRANSACTION_LOG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 3. 인덱스 생성 (성능 향상)
CREATE INDEX IDX_TRANSACTION_MEMBER_TIME ON TRANSACTION_LOG(MEMBER_ID, TRANSACTION_TIME DESC);
CREATE INDEX IDX_TRANSACTION_TYPE ON TRANSACTION_LOG(TRANSACTION_TYPE);
CREATE INDEX IDX_TRANSACTION_ITEM ON TRANSACTION_LOG(RELATED_ITEM_ID);

-- 4. 테스트 데이터 삽입
INSERT INTO TRANSACTION_LOG (LOG_ID, MEMBER_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_TIME, RELATED_ITEM_ID, DESCRIPTION)
VALUES (TRANSACTION_LOG_SEQ.NEXTVAL, 'user001', 'C', 1000000, SYSDATE-5, NULL, '마일리지 충전');

INSERT INTO TRANSACTION_LOG (LOG_ID, MEMBER_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_TIME, RELATED_ITEM_ID, DESCRIPTION)
VALUES (TRANSACTION_LOG_SEQ.NEXTVAL, 'user001', 'B', -500000, SYSDATE-3, 1, '상품 1번 입찰');

INSERT INTO TRANSACTION_LOG (LOG_ID, MEMBER_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_TIME, RELATED_ITEM_ID, DESCRIPTION)
VALUES (TRANSACTION_LOG_SEQ.NEXTVAL, 'user002', 'B', -600000, SYSDATE-2, 1, '상품 1번 입찰');

INSERT INTO TRANSACTION_LOG (LOG_ID, MEMBER_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_TIME, RELATED_ITEM_ID, DESCRIPTION)
VALUES (TRANSACTION_LOG_SEQ.NEXTVAL, 'user001', 'R', 500000, SYSDATE-1, 1, '입찰 환불 (패찰)');

INSERT INTO TRANSACTION_LOG (LOG_ID, MEMBER_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_TIME, RELATED_ITEM_ID, DESCRIPTION)
VALUES (TRANSACTION_LOG_SEQ.NEXTVAL, 'seller01', 'S', 570000, SYSDATE, 1, '상품 1번 판매 수익 (수수료 5% 제외)');

COMMIT;