-- VIP 신청 관리 테이블 생성 SQL

-- 1. VIP_OPTION_REQUEST 테이블 생성 (VIP 신청 관리)
CREATE TABLE VIP_OPTION_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    OPTION_NAME VARCHAR2(100) NOT NULL,
    REQUEST_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT FK_VIP_REQUEST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES USERS(MEMBER_ID)
);

-- 2. VIP_OPTION_REQUEST 시퀀스 생성
CREATE SEQUENCE VIP_OPTION_REQ_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 3. VIP_BENEFIT 테이블 생성 (승인된 VIP 혜택 관리)
CREATE TABLE VIP_BENEFIT (
    BENEFIT_ID NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    OPTION_NAME VARCHAR2(100) NOT NULL,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'SUSPENDED')),
    BENEFIT_OPTION VARCHAR2(200),
    APPROVED_DATE DATE,
    CONSTRAINT FK_VIP_BENEFIT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES USERS(MEMBER_ID)
);

-- 4. VIP_BENEFIT 시퀀스 생성
CREATE SEQUENCE VIP_BENEFIT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 5. VIP_INFO 테이블 생성 (VIP 회원 상세 정보)
CREATE TABLE VIP_INFO (
    MEMBER_ID VARCHAR2(50) PRIMARY KEY,
    PREFERRED_CATEGORY VARCHAR2(100),
    ANNUAL_BUDGET NUMBER,
    VIP_NOTE VARCHAR2(1000),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_VIP_INFO_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES USERS(MEMBER_ID)
);

-- 6. 테스트 데이터 삽입
INSERT INTO VIP_OPTION_REQUEST (REQUEST_ID, MEMBER_ID, OPTION_NAME, STATUS, REQUEST_DATE) 
VALUES (VIP_OPTION_REQ_SEQ.NEXTVAL, 'user001', '골드', 'PENDING', SYSDATE);

INSERT INTO VIP_OPTION_REQUEST (REQUEST_ID, MEMBER_ID, OPTION_NAME, STATUS, REQUEST_DATE) 
VALUES (VIP_OPTION_REQ_SEQ.NEXTVAL, 'user002', '다이아', 'PENDING', SYSDATE-1);

INSERT INTO VIP_OPTION_REQUEST (REQUEST_ID, MEMBER_ID, OPTION_NAME, STATUS, REQUEST_DATE) 
VALUES (VIP_OPTION_REQ_SEQ.NEXTVAL, 'user003', '골드', 'APPROVED', SYSDATE-2);

INSERT INTO VIP_OPTION_REQUEST (REQUEST_ID, MEMBER_ID, OPTION_NAME, STATUS, REQUEST_DATE) 
VALUES (VIP_OPTION_REQ_SEQ.NEXTVAL, 'user004', '다이아', 'REJECTED', SYSDATE-3);

-- 7. 승인된 VIP 혜택 데이터
INSERT INTO VIP_BENEFIT (BENEFIT_ID, MEMBER_ID, OPTION_NAME, START_DATE, STATUS, APPROVED_DATE) 
VALUES (VIP_BENEFIT_SEQ.NEXTVAL, 'user003', '골드', SYSDATE-2, 'ACTIVE', SYSDATE-1);

-- 8. VIP 회원 정보
INSERT INTO VIP_INFO (MEMBER_ID, PREFERRED_CATEGORY, ANNUAL_BUDGET, VIP_NOTE) 
VALUES ('user003', '회화', 5000000, '현대 미술에 관심이 많습니다.');

COMMIT;